Add Manheimer electron-ion scattering model
ModernElectron/WarpX pull request #133
Opened 2021-12-31 01:24 UTC by roelof-groenewald

2021-12-31 03:01 UTC, roelof-groenewald commented on mewarpx/mewarpx/utils_store/util.py
> +def interpolate_from_grid(coords, grid):
I expect this function can be optimized some, perhaps by using Numba. If we can get it sufficiently fast to be competitive with the C++ implementation of the same function (in `/Source/Particles/Gather/ScalarFieldGather.cpp`) we can move our Schottky enhancement implementation completely back to Python which would save us needing to inject an intermediate set of particles just to have them distributed to the proper tiles before upweighting them.

2022-01-04 23:06 UTC, peterscherpelz requested changes
Some important comments, but no core problems. Good stuff!

2022-01-04 23:06 UTC, peterscherpelz commented on mewarpx/mewarpx/coulomb_scattering.py
> +            dif[idx] = isotropized_vels[:, 2]**2 # v_mag[idx]**2
What is the comment in this line for?

2022-01-04 23:06 UTC, peterscherpelz commented on mewarpx/mewarpx/coulomb_scattering.py
> +            # print('delta energy = %.3f eV' % (E_init - E_final))
Might be good to update the constants in the comments, and the print statement to use f-formatting, so that the commented portions are up to date.

2022-01-04 23:06 UTC, peterscherpelz commented on mewarpx/mewarpx/utils_store/util.py
> +            f"simulation has {mwxrun.dim} dimensions."
```suggestion
            f"There were {coords.shape[0]} coordinate values given but the  "
            f"simulation has {mwxrun.dim} dimensions."
```
In case too many dimensions were passed, this language is more general.

2022-01-04 23:06 UTC, peterscherpelz commented on mewarpx/mewarpx/utils_store/util.py
> +        weights[mwxrun.coord_map['y']] = y_grid - lower_node[mwxrun.coord_map['y']]
```suggestion
    # Build up coordinate (indexes, spacing, and bounds)
    # all supported dimensions have a z coordinate
    coord_specs = [(mwxrun.coord_map['z'], mwxrun.dz, mwxrun.zmin)]

    if mwxrun.dim > 1:
        if mwxrun.geom_str == 'RZ':
            coord_specs.append((mwxrun.coord_map['r'], mwxrun.dr, mwxrun.rmin))
        else:
            coord_specs.append((mwxrun.coord_map['x'], mwxrun.dx, mwxrun.xmin))
    if mwxrun.dim == 3:
        coord_specs.append((mwxrun.coord_map['y'], mwxrun.dy, mwxrun.ymin))

    # Iterate over all dimensions
    for idx, dx, xmin in coord_specs:
        x_grid = (coords[idx] - xmin) / dx
        lower_node[idx] = np.floor(x_grid).astype(int)
        weights[idx] = x_grid - lower_node[idx]

```

2022-01-04 23:06 UTC, peterscherpelz commented on mewarpx/mewarpx/utils_store/util.py
> +        fpos += grid[lower_node[0] + 1, lower_node[1] + 1] * (1.0 - weights[0]) * (1.0 - weights[1])
Have you checked you don't have these backwards? weights is tiny just above the coordinate, largest far above the coordinate. So I think the lower nodes should use (1 - weights) and the higher nodes use weights

2022-01-04 23:06 UTC, peterscherpelz commented on mewarpx/tests/test_coulomb_scattering.py
> +
Maybe we should put this into our solver file in the main code? It seems like we might like to reuse it; someone won't know it exists if it's only here.

2022-01-04 23:06 UTC, peterscherpelz commented on mewarpx/tests/test_coulomb_scattering.py
> +        lower_bound=[-PERIOD/2.0, 0.], upper_bound=[PERIOD, ZMAX],
-PERIOD/2 to PERIOD seems weird

2022-01-04 23:29 UTC, roelof-groenewald commented on mewarpx/mewarpx/utils_store/util.py
> +        fpos += grid[lower_node[0] + 1, lower_node[1] + 1] * (1.0 - weights[0]) * (1.0 - weights[1])
I do have it backwards, thanks for catching! In this case the charge density is pretty much constant which is why nothing very strange happened due to this particular bug.

2022-01-04 23:35 UTC, roelof-groenewald commented on mewarpx/mewarpx/coulomb_scattering.py
> +            dif[idx] = isotropized_vels[:, 2]**2 # v_mag[idx]**2
It is for testing the implementation without doing the velocity isotropization for outliers but instead just ignoring them. If that case is used `Q1[idx] = 0` and `Q2[idx] = 0` should also be set. I can remove the comment if you'd like.

2022-01-04 23:37 UTC, roelof-groenewald commented on mewarpx/tests/test_coulomb_scattering.py
> +        lower_bound=[-PERIOD/2.0, 0.], upper_bound=[PERIOD, ZMAX],
Agreed.

2022-01-05 20:10 UTC, peterscherpelz approved these changes
Thanks for the corrections, nothing further from me!

2022-01-05 21:17 UTC, merged