Documentation for Unit Tests
ModernElectron/WarpX pull request #56
Opened 2021-08-23 21:45 UTC by nruof

Included documentation about unit test structure convention and a few links to examples in mewarpx

2021-08-24 19:24 UTC, MKieburtz approved these changes

2021-08-25 21:59 UTC, peterscherpelz requested changes

2021-08-25 21:59 UTC, peterscherpelz commented on mewarpx/docs/unit_test.rst
> +All test files for mwxp are located in the tests directory.  For each pull request
```suggestion
All test files for mewarpx are located in the ``tests`` directory.  For each pull request
```

2021-08-25 21:59 UTC, peterscherpelz commented on mewarpx/docs/unit_test.rst
> +`Test mwxrun <https://github.com/ModernElectron/WarpX/blob/memaster/mewarpx/tests/test_flux_diagnostic.py>`_
Link wasn't updated

2021-08-27 19:50 UTC, KZhu-ME approved these changes
Looks good!

2021-08-27 23:59 UTC, peterscherpelz approved these changes

2021-08-28 00:00 UTC, merged