Picmi mcc
ModernElectron/WarpX pull request #7
Opened 2021-06-28 20:09 UTC by roelof-groenewald

Functionality to run MCC from a python run script.

2021-06-28 20:24 UTC, peterscherpelz requested changes
1 small change. Thanks!

2021-06-28 20:24 UTC, peterscherpelz commented on mewarpx/examples/capacitive_discharge.py
> +v_rms_elec = np.sqrt(minutil.kb_J * T_ELEC / minutil.m_e)
@roelof-groenewald Please replace with WarpX / non-minutil constants and remove that import.

2021-06-28 20:35 UTC, peterscherpelz approved these changes

2021-06-28 21:21 UTC, nruof commented on Python/pywarpx/picmi.py
> +
Why does the newcollision function append to "collisions_list" when the "collision" also gets appended in the last line of 
"initialize_inputs" in "MCCCollisions"?

2021-06-28 22:44 UTC, MKieburtz reviewed
I don't see any problems other than what Nich pointed out

2021-06-28 23:16 UTC, roelof-groenewald commented
Thanks @nruof, nice catch!

2021-06-29 14:38 UTC, peterscherpelz commented
@nruof @MKieburtz Can one of you leave an approving review then? You can then merge it.

2021-06-29 16:29 UTC, MKieburtz approved these changes
Looks good

2021-06-29 16:59 UTC, merged