Sim Control Flow Feature Addition
ModernElectron/WarpX pull request #8
Opened 2021-06-29 17:49 UTC by nruof

Class that allows a user to define a list of function criteria to be evaluated over a set of diagnostic steps in a simulation.

Example:

steps_per_loop = 10
        while (sim_control.check_criteria()):
            sim.step(steps_per_loop)

2021-06-29 19:44 UTC, kzhu-ME reviewed
Looks good, just a have a few minor suggestions.

2021-06-29 19:44 UTC, kzhu-ME commented on mewarpx/mewarpx/sim_control.py
> +    def add_checker(self, criteria=None, crit_args=None):
Not a big deal, but there doesn't seem to be a use case for where `criteria = None`, so `criteria` shouldn't have a default value of `None`.

2021-06-29 19:44 UTC, kzhu-ME commented on mewarpx/mewarpx/sim_control.py
> +            self.crit_args_list.append({})
Here you don't need the if else statement/branching logic if you set the default value of `crit_args` to `crit_args={}`

2021-06-29 19:44 UTC, kzhu-ME commented on mewarpx/mewarpx/sim_control.py
> +        returns True is all criteria are True otherwise returns False
```suggestion
        returns True if all criteria are True otherwise returns False
```
A small typo

2021-06-29 21:49 UTC, roelof-groenewald requested changes
I left some comments on suggested changes, please let me know if anything is unclear.

2021-06-29 21:49 UTC, roelof-groenewald commented on mewarpx/mewarpx/sim_control.py
> +    def __init__(self, criteria, criteria_args, max_loops=None, **kwargs):
This class should definitely allow for the scenario where `max_loops` is the only argument specified. So I'd suggest giving default values of `None` for `criteria` and `criteria_args` and not setting a default value for max_loops. Then add check in the __init__ function that max_loops >= 1.

2021-06-29 21:49 UTC, roelof-groenewald commented on mewarpx/mewarpx/sim_control.py
> +            return True
With the forcing of a `max_loops` value from above I'd change this function to something like
```suggestion
        self.check_increment += 1
        if self.check_increment >= self.max_loops:
            print('Max loops reached.')
            return False
            
        for i, func in enumerate(self.crit_list):
            if not self.crit_list[i](**self.crit_args_list[i]):
                print(("Termination due to criteria {}").format(func.__name__))
                return False
```
But actually even better than using `max_loops` argument would be to use a `max_steps` argument and then calling the mewarpx function that returns the simulation step number when evaluating whether to terminate.

2021-06-30 15:48 UTC, peterscherpelz requested changes
Lots of comments, mostly for writing clean code in the long-term. Thanks!

2021-06-30 15:48 UTC, peterscherpelz commented on mewarpx/mewarpx/sim_control.py
> +
```suggestion


```

2021-06-30 15:48 UTC, peterscherpelz commented on mewarpx/mewarpx/sim_control.py
> +import time
Remove unused import

2021-06-30 15:48 UTC, peterscherpelz commented on mewarpx/mewarpx/sim_control.py
> +import time
and numpy, psutil, _libwarpx, mwxrun - or at least comment out if they'll be later used as you expand this.

2021-06-30 15:48 UTC, peterscherpelz commented on mewarpx/mewarpx/sim_control.py
> +        Arguments:
Newline before Arguments will make autodoc happier. Then indent criteria and criteria_args by 4 spaces relative to arguments.
Also add max_loops and kwargs to Arguments list
You should either say 'read check_criteria' documentation below, or move info about criteria up here - eg when do we want it to return True vs False.

2021-06-30 15:48 UTC, peterscherpelz commented on mewarpx/mewarpx/sim_control.py
> +    def __init__(self, criteria, criteria_args, max_loops=None, **kwargs):
I would not separate criteria and criteria_args into separate lists. (I don't like the format of having to match up correct criteria with their args.)
A nice format might be a list of criteria, and each criteria can either be a function or a tuple of `(function, kwargs)`.
```
if callable(criteria[i]):
   self.crit_list.append(criteria[i])
   self.crit_args_list.append({})
else:
   self.crit_list.append(criteria[i][0])
   self.crit_args_list.append(criteria[i][1])
```

2021-06-30 15:48 UTC, peterscherpelz commented on mewarpx/mewarpx/sim_control.py
> +        criteria_args: list of kwargs for each criteria
dict, not list

2021-06-30 15:48 UTC, peterscherpelz commented on mewarpx/mewarpx/sim_control.py
> +            self.crit_args_list.append({})
You actually don't want to do this as a general rule.
https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html or a more verbose explanation 
https://towardsdatascience.com/python-pitfall-mutable-default-arguments-9385e8265422

2021-06-30 15:48 UTC, peterscherpelz commented on mewarpx/mewarpx/sim_control.py
> +                if not keep_going:
I would not short-circuit these function evaluations if one returns false. Sometimes we'll want to install functions that both handle diagnostics and tell something to terminate. It'll probably be most straightforward if those all still run on the last time through things.

2021-06-30 15:48 UTC, peterscherpelz commented on mewarpx/mewarpx/sim_control.py
> +                if not keep_going:
You can keep the same print info by starting with an empty string, then add to it for each criteria that returns False.

2021-07-01 16:28 UTC, kzhu-ME approved these changes
Aside from the changes Peter suggested, everything else looks good to me!

2021-07-01 16:36 UTC, MKieburtz approved these changes
Cool stuff

2021-07-01 19:05 UTC, nruof commented
I tested out the changes.  eval_max_steps terminates the simulation properly a custom criteria function also terminates properly.  Changes are good.

2021-07-01 19:17 UTC, roelof-groenewald approved these changes
Looks good to me.

2021-07-01 19:18 UTC, merged