Add support for multiple EBs with different potentials
ModernElectron/WarpX pull request #91
Opened 2021-10-26 00:14 UTC by roelof-groenewald

Remaining issue that I'm currently aware of:
- The EB potential really should be specified with form `if(explicit_function >= 0, V, ...)` but when using `>=` I'm getting an error `ParmParse::addDefn(): no values for definition warpx.eb_potential(x,y,z,t)`.

With simple conductors with fixed voltage values the current implementation does seem to work:
![two_cylinders](https://user-images.githubusercontent.com/40245517/138787695-7815a332-56e8-4c80-862b-c7f97dfbcf33.png)

2021-10-26 17:36 UTC, peterscherpelz requested changes
Tiny comment plus the discussed-in-person simplification of voltage expressions. Otherwise a great start to multiple EBs!

I'm glad the code generating the pulse expression didn't get more complex, even if the resulting expression did...

2021-10-26 17:36 UTC, peterscherpelz commented on mewarpx/tests/test_assemblies.py
> +    assert np.allclose(phi, ref_phi, 0.001)
```suggestion
    assert np.allclose(phi, ref_phi, rtol=0.001)
```
Just saves people from looking up whether rtol or atol comes first/clearer code.

2021-10-26 19:09 UTC, roelof-groenewald commented on mewarpx/tests/test_assemblies.py
> +    assert np.allclose(phi, ref_phi, 0.001)
There are a few more places in the same file where the same change is applicable, so I'll just add it in along with the next commit.

2021-10-26 19:11 UTC, KZhu-ME reviewed
Looks good overall, will re-review when `_install_in_simulation` is refactored.

2021-10-26 21:27 UTC, KZhu-ME requested changes
Just a few suggestions.

2021-10-26 21:27 UTC, KZhu-ME commented on Source/Python/WarpXWrappers.cpp
> +        for (amrex::ParIter<0,0,PIdx::nattribs, 0, amrex::PinnedArenaAllocator> pti(particle_buffer, lev); pti.isValid(); ++pti, ++i) {}
This is an unused copy of the for loop below right?
```suggestion
```

2021-10-26 21:27 UTC, KZhu-ME commented on Source/Python/WarpXWrappers.cpp
> +        amrex::ParticleReal** data = (amrex::ParticleReal**) malloc(*num_tiles*sizeof(typename WarpXParticleContainer::ParticleType*));
Are `*particles_per_tile` and `data` guaranteed to be filled/terminated correctly? If not it might be better to use `calloc` rather than `malloc`, as `calloc` will zero the allocated memory for you to prevent reading from uninitialized memory.

2021-10-26 21:27 UTC, KZhu-ME commented on mewarpx/mewarpx/assemblies.py
> +                    my_idx_list = []
Could we rename `my_idx_list` to something like `temp_idx_list` to be more descriptive of it's function?

2021-10-26 21:33 UTC, roelof-groenewald commented on Source/Python/WarpXWrappers.cpp
> +        for (amrex::ParIter<0,0,PIdx::nattribs, 0, amrex::PinnedArenaAllocator> pti(particle_buffer, lev); pti.isValid(); ++pti, ++i) {}
It is not quite unused. It is the unfortunate way currently used in all functions of this type to get the appropriate value of `i`.

2021-10-26 21:34 UTC, roelof-groenewald commented on Source/Python/WarpXWrappers.cpp
> +        amrex::ParticleReal** data = (amrex::ParticleReal**) malloc(*num_tiles*sizeof(typename WarpXParticleContainer::ParticleType*));
Nice suggestion, but I think I'll leave it as is for now to match the way the other functions like this is done. Feel free to open an upstream PR to switch all of them if you'd like.

2021-10-26 23:20 UTC, KZhu-ME commented on Source/Python/WarpXWrappers.cpp
> +        for (amrex::ParIter<0,0,PIdx::nattribs, 0, amrex::PinnedArenaAllocator> pti(particle_buffer, lev); pti.isValid(); ++pti, ++i) {}
I see, can you add a comment that explain this? It seems like it'd be important for future reference.

2021-10-26 23:21 UTC, KZhu-ME commented on Source/Python/WarpXWrappers.cpp
> +        amrex::ParticleReal** data = (amrex::ParticleReal**) malloc(*num_tiles*sizeof(typename WarpXParticleContainer::ParticleType*));
Sounds good, we can put it in the backlog if it causes issues in the future. From previous debugging, it seems like there are quite a few instances of reading uninitialized memory, but it doesn't seem to cause breaking problems for the most part.

2021-10-26 23:22 UTC, KZhu-ME approved these changes
Looks good!

2021-10-27 00:01 UTC, peterscherpelz approved these changes
One main question: Where do we control flags for compatibility/incompatibility with different dimensions? I'm not sure where we should record that the EB scraping is only implemented for 2D. Otherwise it looks great!

2021-10-27 00:19 UTC, KZhu-ME commented
> One main question: Where do we control flags for compatibility/incompatibility with different dimensions? I'm not sure where we should record that the EB scraping is only implemented for 2D. Otherwise it looks great!

On line 153 the TODO statement, we could add a raise NotImplementedError there if the simulation is in 3D.

2021-10-27 05:40 UTC, roelof-groenewald commented
@peterscherpelz How about the changes from the newest commit to deal with `XZ` versus `XYZ` sims (there is still a lot of incompatibilities with RZ to sort out).

2021-10-27 16:12 UTC, KZhu-ME commented on mewarpx/mewarpx/assemblies.py
> +                        raise RuntimeError(
```suggestion
                        raise NotImplementedError(
```
This works but I think a NotImplementedError would be more descriptive.

2021-10-27 18:34 UTC, merged